Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd C:\PHDMSInterface

C:\PHDMSInterface>python bin\invoice_K302ZH.py
C:\Program Files\Python38\lib\site-packages\grequests.py:22: MonkeyPatchWarning:
 Monkey-patching ssl after ssl has already been imported may lead to errors, inc
luding RecursionError on Python 3.6. It may also silently lead to incorrect beha
viour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/
gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.uti
l (C:\\Program Files\\Python38\\lib\\site-packages\\urllib3\\util\\__init__.py)'
, 'urllib3.util.ssl_ (C:\\Program Files\\Python38\\lib\\site-packages\\urllib3\\
util\\ssl_.py)'].
  curious_george.patch_all(thread=False, select=False)
C:\Program Files\Python38\lib\site-packages\sqlalchemy\ext\declarative\clsregist
ry.py:125: SAWarning: This declarative base already contains a class with the sa
me class name and module name as src.models.nav.K302 Zhuhai JJ$DMSInterfaceInfo,
 and will be replaced in the string-lookup table.
  util.warn(
Traceback (most recent call last):
  File "bin\invoice_K302ZH.py", line 81, in <module>
    entry_no = main(company_code, api_code, retry=False)
  File "bin\invoice_K302ZH.py", line 34, in main
    xml_src_path, data = invoiceHeader_obj.load_data(api_setup, file_path=file_p
ath)
  File "C:\PHDMSInterface\src\dms\base.py", line 220, in load_data
    is_integrity, keys = self.is_integrity(res.data, apiSetup.Company_Code, apiS
etup.API_Code)
  File "C:\PHDMSInterface\src\dms\base.py", line 174, in is_integrity
    res_bool2, res_keys2 = self._is_integrity(data_dict, company_code, api_code)

  File "C:\PHDMSInterface\src\dms\invoice.py", line 115, in _is_integrity
    data_list = data_dict["Transaction"][self.BIZ_NODE_LV1]
KeyError: 'Invoice'

C:\PHDMSInterface>